name: Run PIB Scraper

on:
  # Manual trigger
  workflow_dispatch:
  # Schedule to run daily at 00:00 UTC (uncomment when ready)
  # schedule:
  #   - cron: '0 0 * * *'

jobs:
  run-scraper:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests beautifulsoup4 pandas
        
    - name: Run PIB scraper
      run: |
        python pib_scraper.py
        
    - name: Upload scraped data
      uses: actions/upload-artifact@v3
      with:
        name: pib-scraped-data
        path: |
          data/raw/
          data/processed/
          pib_scraper.log
